### ISSUE TITLE
How does it differs from node-calls-python ?

### ISSUE THREAD

**Issue by Bonjour123** [mmomtchev/pymport#199]
The package [node-calls-python](https://www.npmjs.com/package/node-calls-python) seems to achieve the same goal as you, using the same way (using the N-API and Python C API).
Any difference in the implementations, limits, performances in your opinion ?

For further reference, here are some packages achieving the same goals with different means:

[Pybridge](https://github.com/marcj/pybridge) is using child_process, communicates through stdin/stdout, and uses serialization/deserialization for data exchange.

[Pyopide](https://github.com/pyodide/pyodide) is running inside the browser using WebAssembly->slower than other solutions

**Comment by mmomtchev** [comment]
Neither of those three packages comes anywhere near the performance of `pymport`. The difference is in orders of magnitude. `pymport` has been made to allow using Python libraries from Node.js at native speeds. `Pyodide`'s main goal is to use Python software on the web. `Pybridge` is a very primitive implementation, it comes down to launching an external Python interpreter. `node-calls-python` allows to run Python code at native speeds, but does not allow to use a library - it is meant for programs that have a single entry point.

**Comment by Bonjour123** [comment]
Ok, thank you for the quick reply and the clarification.
You have been honest about the [current limitations](https://github.com/mmomtchev/pymport/wiki#known-issues). I couldn't find these issues  in node-calls-python (NCP) docs.

Since NCP seems more mature (please take no offence here, I respect the huge and quality work you're doing, but they are at least five contributors), wouldn't it be a good option to use NCP, define a python program that returns the libs I want to use, to achieve the same as Pymport do ?

**Comment by mmomtchev** [comment]
If you can use Python, why not. `pymport` is for using Python libraries from Node.js. This is what it does and it is the only package that does it.

Hopefully you do not expect that you will send me compromising with my ongoing legal matters in order to find more contributors :laughing:

**Comment by Bonjour123** [comment]
Understood :)

No ahah. And to be honest, your current legal disputes seems a bit _paranoiac_ from an outer perspective, and from the data I've read from your github and SO profiles, while I do understand I certainly dont' have all information.
But being French and having passed interviews with 2 companies you mentioned, a friend of mine working for another one (you mentioned), this all seems very hard to believe, even more with countless open source organizations being involved, this all doesn't make a lot of sense IMHO.
Anyway I really sincerely hope things will get better for you !

**Comment by mmomtchev** [comment]
Yeah, I already expected that the *paranoia* subject was coming...
