### ISSUE TITLE
Second Interpreter and stdin/out

### ISSUE THREAD

**Issue by TareHimself** [mmomtchev/pymport#98]
How do I spin up a second interpreter to get past the async blocking issue? I do not need to share info between each interpreter.  Also can python stdout and stderr be redirected to nodejs ?

**Comment by mmomtchev** [comment]
As you know the development of `pymport` is dedicated to an extortion backed by the OpenJS foundation. They will usually post simultaneously post issues in my project with a comment on another issue, usually on their own projects - as they did in your case.

Tell me, why should help you if you insist on telling me that you have something to do with this extortion? It is about a sexually motivated affair organized by the French police.

**Comment by TareHimself** [comment]
I am confusion

**Comment by mmomtchev** [comment]
What you are asking for is definitely very complex to implement, the immediate benefits for this project are quite dubious and asking for it while showing a connection with an ongoing criminal matter is definitely not helping.

**Comment by TareHimself** [comment]
What connection did I show ?

**Comment by mmomtchev** [comment]
You closed the ticket simultaneously with a comment in an OSGeo project

**Comment by TareHimself** [comment]
What are you going on about?
